export const UPDATE_SPENDING_LIMIT = 'UPDATE_SPENDING_LIMIT';
export const UPDATE_WIDTH = 'UPDATE_WIDTH';
export const UPDATE_AVAILABLE_BALANCE = 'UPDATE_AVAILABLE_BALANCE';
export const UPDATE_CARD_DETAILS = 'UPDATE_CARD_DETAILS';
